### ISSUE TITLE
installation/running issue

### ISSUE THREAD

**Issue by clach04** [moltenform/scite-with-python#2]
With the Windows build https://github.com/moltenform/scite-with-python/releases/tag/v0.7.4 out-of-box I was not able to get any of the python "stuff" to work, e.g. "Language" menu was empty and no styling/options in Scite were set.

I figured out that the properties file(s) where not being loaded, so after some grep'ing of the code I realized that the scite home directory needed to be set to the properties directory:

https://github.com/moltenform/scite-with-python/blob/6a685e55d159cd8850a6765fcc3e37f1df587403/src/scite/scite/win32/SciTEWin.cxx#L442

e.g.:

    C:\Programs\scite_with_python_0_7_4_win32>set SciTE_HOME=%CD%
    C:\Programs\scite_with_python_0_7_4_win32>scite

I didn't see anything in the docs about this.

Is this the best/recommended way or is there an alternative approach I should take?

I'm really delighted to have found this project! Thanks for posting this!

**Comment by benf-write** [comment]
Thanks!

I'm not sure why the properties are not being loaded. It downloaded the zip again and it works fine on my machine, and I believe the default scite home defaults to the current directory. Is it possible SciTE_HOME is being set to something else, or that scite.exe is being run from a separate directory? (For example a windows lnk shortcut has a field for 'run in directory' that isn't always the same).

**Comment by clach04** [comment]
Thanks for the quick response @benf-write . I must have got my self confused, you guessed correctly there was (it turns out) an existing scite_home variable. All my fault :-( Thank you!
